name: Crystal CI

on: [push]

jobs:
  build:

    strategy: 
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: ubuntu-latest, crystal: 0.36.0}
          - {os: ubuntu-latest, crystal: 0.34.0}
          - {os: ubuntu-latest, crystal: 1.0.0}
    runs-on: ${{matrix.os}}
    
    # runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Crystal Ameba Linter
      uses: crystal-ameba/github-action@v0.2.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
