name: Crystal CI

on: [push]

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        crystal: [latest, nightly, 1.0.0, 0.34.0, 0.35.1, 0.36.0]
    runs-on: ubuntu-latest

    steps:
    - uses: oprypin/install-crystal@v1
      with:
        crystal: ${{matrix.crystal}}
    - name: Crystal Ameba Linter
      uses: crystal-ameba/github-action@v0.2.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - run: crystal tool format && git diff --exit-code
      if: matrix.crystal == 'latest'
